"""Build the ACF static site. Content comes from the archived official pages."""
from pathlib import Path
import json,html,re,shutil,sys
ROOT=Path(__file__).parent
DIST=ROOT/'dist'; DIST.mkdir(exist_ok=True)
ORIGIN='https://acf-performance-fidas.fidelis07dev.chatgpt.site'
OFFICIAL='https://www.acfperformance.com'
WA='https://wa.me/5511984496047'
PLAYLIST='https://www.youtube.com/playlist?list=PL9NEEeEVkyUJ81uBiWzk6dpYWVBNh85I6'
E=html.escape
def button(label,url=WA,secondary=False):
    return f'<a class="btn {"btn-line" if secondary else ""}" href="{E(url)}">{label}<span aria-hidden="true">↗</span></a>'
def label(text): return f'<p class="eyebrow"><span aria-hidden="true">/</span> {text}</p>'
def link(label,url):return f'<a class="arrow-link" href="{url}">{label} <span aria-hidden="true">↗</span></a>'
def placeholder(text):return f'<span class="missing">[PREENCHER] {text}</span>'
def logo():return '<img src="/assets/logo.png" width="175" height="69" alt="ACF Performance">'
def header(active):
    nav=[('Início','/'),('ACF','/acf/'),('Performance','/performance/'),('Education','/education/'),('Media','/media/'),('Portal','/portal/'),('Contato','/contato/')]
    items=''.join(f'<a href="{u}" {"aria-current=page" if active==u else ""}>{n}</a>' for n,u in nav)
    return f'<a class="skip" href="#main">Pular para o conteúdo</a><div class="topline"><span>SÃO PAULO / BRASIL</span><a href="{OFFICIAL}/area-do-cliente/">Área do cliente ↗</a></div><header class="header"><a class="brand" href="/">{logo()}</a><button class="menu" aria-controls="navigation" aria-expanded="false">Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Navegação principal">{items}</nav>{button("Pedir orçamento")}</header>'
def footer():
    return f'''<section class="closing wrap"><div>{label('SEU PRÓXIMO PROJETO')}<h2>VAMOS FALAR<br>DE <em>PERFORMANCE?</em></h2></div><div><p>Conte qual é o seu carro e o que você busca.<br>Converse com a equipe ACF.</p>{button('Pedir orçamento no WhatsApp')}<p class="small">(11) 98449-6047</p></div></section><footer class="footer wrap"><div class="footer-grid"><a class="brand" href="/">{logo()}</a><div><strong>ENCONTRE A ACF</strong><p>Av. Doutor Ricardo Jafet, 1050<br>Vila Mariana · São Paulo, SP<br>CEP 04260-000</p></div><div><strong>EXPLORE</strong><a href="/acf/1/historia/">História</a><a href="/acf/3/equipe-performance/">Equipe Performance</a><a href="/education/">ACF Education</a><a href="{OFFICIAL}/area-do-cliente/">Área do cliente ↗</a></div><div><strong>CONECTE-SE</strong><a href="https://www.instagram.com/acfperformance">Instagram ↗</a><a href="https://www.youtube.com/acfperformance">YouTube ↗</a><a href="https://www.facebook.com/acfperformance">Facebook ↗</a><a href="https://www.lolja.com.br/acfperformance">Loja ACF ↗</a></div></div><div class="footer-bottom"><span>© 2026 ACF Performance</span><a href="{OFFICIAL}/item/1/">Política de privacidade ↗</a><a href="#top">Voltar ao topo ↑</a></div></footer>'''
def page(path,title,description,body,active=None,schema=None):
    business={'@context':'https://schema.org','@type':'AutoRepair','@id':ORIGIN+'/#business','name':'ACF Performance','url':ORIGIN,'telephone':'+55-11-98449-6047','logo':ORIGIN+'/assets/logo.png','address':{'@type':'PostalAddress','streetAddress':'Avenida Doutor Ricardo Jafet, 1050','addressLocality':'São Paulo','addressRegion':'SP','postalCode':'04260-000','addressCountry':'BR'},'sameAs':['https://www.instagram.com/acfperformance','https://www.youtube.com/acfperformance','https://www.facebook.com/acfperformance']}
    full=f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} | ACF Performance</title><meta name="description" content="{E(description)}"><meta name="robots" content="noindex,nofollow"><link rel="canonical" href="{ORIGIN+path}"><meta property="og:locale" content="pt_BR"><meta property="og:type" content="website"><meta property="og:site_name" content="ACF Performance"><meta property="og:title" content="{E(title)}"><meta property="og:description" content="{E(description)}"><meta property="og:url" content="{ORIGIN+path}"><meta name="twitter:card" content="summary"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700;800&family=Barlow:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/approved-home.css"><script type="application/ld+json">{json.dumps(business,ensure_ascii=False)}</script>{('<script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False)+'</script>') if schema else ''}<script src="/app.js" defer></script></head><body id="top" class="{"home-approved" if path=="/" else "inner-page"}">{header(active or path)}<main id="main">{body}</main>{footer()}</body></html>'''
    target=DIST/path.strip('/')/'index.html' if path!='/' else DIST/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(full.replace('<br>','<br> '),encoding='utf-8')
def masthead(kicker,title,desc,extra=''):
    return f'<section class="page-hero wrap"><a class="crumb" href="/">INÍCIO /</a>{label(kicker)}<h1>{title}</h1><p class="lead">{desc}</p>{extra}</section>'
def courses():
    return f'''<div class="course-grid"><article class="course"><div class="course-top"><span class="code">M01</span><span class="tag">PRESENCIAL</span></div><h3>ENTENDA O MOTOR.<br>DOMINE A BASE.</h3><p>Módulo 1: motores de ciclo Otto, injeção eletrônica e calibração com FuelTech.</p><dl><div><dt>Duração</dt><dd>2 dias / 16 horas</dd></div><div><dt>Prática</dt><dd>Veículo no dinamômetro</dd></div><div><dt>Pré-requisito</dt><dd>Ser entusiasta</dd></div></dl>{button('Conhecer o Módulo 1','/education/info/1/modulo-1-presencial/')}</article><article class="course"><div class="course-top"><span class="code">M02</span><span class="tag">HÍBRIDO</span></div><h3>DA CALIBRAÇÃO<br>À APLICAÇÃO REAL.</h3><p>Módulo 2: estratégias de ECUs originais, equipamentos de reprogramação e o negócio de tuning.</p><dl><div><dt>Online ao vivo</dt><dd>5 dias / 15 horas</dd></div><div><dt>Presencial</dt><dd>2 dias / 16 horas</dd></div><div><dt>Pré-requisito</dt><dd>Módulo 1 obrigatório</dd></div></dl>{button('Conhecer o Módulo 2','/education/info/5/modulo-2-hibrido-parte-online-e-parte-presencial/')}</article></div>'''
def media_cards():
    return f'''<div class="media-grid"><a class="video-card" href="https://www.youtube.com/acfperformance"><img src="/assets/video.jpg" alt="Conteúdo automotivo do canal ACF Performance" width="700" height="440" loading="lazy"><span class="play" aria-hidden="true">▶</span><div><span class="eyebrow">YOUTUBE / ACF PERFORMANCE</span><h3>O CONHECIMENTO<br>ACELERA AQUI.</h3><span>Conheça o canal ↗</span></div></a><div class="media-side"><a class="media-mini" href="{PLAYLIST}"><img src="/assets/tunercast.jpg" alt="Tunercast" width="121" height="121" loading="lazy"><div><span class="eyebrow">PODCAST</span><h3>TUNERCAST</h3><p>Preparação, potência e alta performance.</p><span>Ouça os episódios ↗</span></div></a><a class="media-mini" href="https://www.instagram.com/acfperformance"><span class="ig-symbol" aria-hidden="true">◎</span><div><span class="eyebrow">INSTAGRAM</span><h3>@ACFPERFORMANCE</h3><p>Acompanhe os registros de carros e os bastidores da ACF.</p><span>Abrir o perfil ↗</span></div></a></div></div>'''
def results():
    return f'''<section class="section wrap results" id="resultados"><div class="section-head"><div>{label('02 / RESULTADOS PUBLICADOS')}<h2>PERFORMANCE<br>QUE SE <em>MEDE.</em></h2></div><p>BMW M3 F80 · S55<br>Compare os números publicados pela ACF.</p></div><div class="result-grid"><div class="result-visual"><img src="/assets/m3.jpg" alt="BMW M3 F80 do catálogo ACF, fotografado na oficina" width="900" height="600" loading="lazy"><div class="result-caption"><span>BMW M3 F80 / S55</span><a href="/performance/?version=96">Ver os pacotes ↗</a></div></div><div class="result-data"><div class="segmented" role="group" aria-label="Comparação do pacote BMW M3"><button type="button" data-stage="1" aria-pressed="true">STAGE 1</button><button type="button" data-stage="2" aria-pressed="false">STAGE 2</button></div><div id="result-comparison" aria-live="polite"><div class="metric"><span>POTÊNCIA</span><strong><small>431</small><span aria-hidden="true"> → </span><span id="power">501</span> <small>HP</small></strong><span class="gain" id="power-gain">+70 HP</span></div><div class="metric"><span>TORQUE</span><strong><small>550</small><span aria-hidden="true"> → </span><span id="torque">680</span> <small>Nm</small></strong><span class="gain" id="torque-gain">+130 Nm</span></div></div><p class="small muted">Original → preparado. Valores do catálogo ACF, consultado em 22/09/2026. Confirme a aplicação com a equipe.</p><details class="dyno"><summary>Ver o gráfico de dinamômetro do Stage 2</summary><a href="/assets/m3-dyno.jpg" target="_blank" rel="noopener"><img src="/assets/m3-dyno.jpg" alt="Dinamômetro Stage 2 BMW M3: 457,49 WHP e 70,47 kgf·m; curvas de potência e torque por rotação" width="920" height="710" loading="lazy"></a><p class="small">Arquivo original ACF: 457,49 WHP e 70,47 kgf·m. A medição nas rodas e suas unidades diferem da tabela comercial. Abra a imagem para ampliar.</p></details></div></div></section>'''
home=f'''<section class="hero"><div class="hero-copy">{label('REMAP & PREPARAÇÃO AUTOMOTIVA / SÃO PAULO')}<h1>POTÊNCIA<br>SOB <em>CONTROLE.</em></h1><p>Reprogramação de motores e pacotes de performance.<br>Conhecimento técnico para transformar a experiência de dirigir.</p><div class="actions">{button('Orçamento no WhatsApp')}{link('Encontre seu pacote','/performance/')}</div><div class="hero-signature"><span>QUALIDADE.</span><span>PRESTEZA.</span><span>CONFIABILIDADE.</span></div></div><div class="hero-photo"><img src="/assets/hero.jpg" alt="BMW vermelho no dinamômetro da ACF Performance" width="1920" height="600" fetchpriority="high"><span class="photo-label">ACF PERFORMANCE / NO DINAMÔMETRO</span><span class="photo-corner" aria-hidden="true">ACF</span></div></section><div class="proof-bar wrap"><div><strong>DESDE 2012</strong><span>Soluções de performance</span></div><div><strong>5 CONTINENTES</strong><span>Projetos BMW pelo mundo</span></div><div><strong>100+ BMW</strong><span>Preparados fora do Brasil</span></div>{link('Nossa trajetória','/acf/1/historia/')}</div><section class="section wrap"><div class="section-head"><div>{label('01 / PERFORMANCE')}<h2>O SEU CARRO.<br>A SUA <em>EVOLUÇÃO.</em></h2></div><div><p>Selecione fabricante, modelo, ano e motor.<br>Conheça os pacotes disponíveis para o seu projeto.</p>{link('Explorar o catálogo completo','/performance/')}</div></div><div class="service-row"><a href="/performance/"><span class="code">01</span><h3>REPROGRAMAÇÃO<br>DE ECU</h3><p>Consulte calibrações, aplicações e ganhos publicados para cada motorização.</p><span class="service-arrow" aria-hidden="true">↗</span></a><a href="/performance/"><span class="code">02</span><h3>PACOTES DE<br>PERFORMANCE</h3><p>Compare os stages, os valores e as condições de cada pacote.</p><span class="service-arrow" aria-hidden="true">↗</span></a><a href="/performance/?category=programavel"><span class="code">03</span><h3>INJEÇÃO<br>PROGRAMÁVEL</h3><p>Aplicações aspiradas e turbo presentes no catálogo ACF.</p><span class="service-arrow" aria-hidden="true">↗</span></a></div></section>{results()}<section class="story-band wrap"><div>{label('ACF / CONHECIMENTO APLICADO')}<h2>ANTES DA POTÊNCIA,<br>EXISTE <em>ENGENHARIA.</em></h2></div><div><p>De São Paulo para cinco continentes. Uma história que começou com Subaru e Mitsubishi e se expandiu com projetos BMW.</p><div class="actions">{link('Conheça a história','/acf/1/historia/')}{link('Nossa equipe','/acf/3/equipe-performance/')}</div></div></section><section class="section light wrap"><div class="section-head"><div>{label('03 / ACF EDUCATION')}<h2>APRENDA COM<br>QUEM <em>CALIBRA.</em></h2></div><p>Teoria, prática e dinamômetro.<br>Cursos com Ricardo Freitas, fundador e tuner da ACF.</p></div>{courses()}</section><section class="section wrap"><div class="section-head"><div>{label('04 / MEDIA')}<h2>MUITO ALÉM<br>DO <em>CAPÔ.</em></h2></div>{link('Explore o universo ACF','/media/')}</div>{media_cards()}</section>'''
approved_hero=f'''<section class="dramatic-hero" aria-labelledby="dramatic-title"><img class="dramatic-scene" src="/assets/hero-performance.png" alt="" width="1586" height="992" fetchpriority="high"><p class="dramatic-side dramatic-left">REMAP E PREPARAÇÃO<br>AUTOMOTIVA EM SÃO PAULO</p><p class="dramatic-side dramatic-right">QUALIDADE.<br>PRESTEZA.<br>CONFIABILIDADE.</p><div class="dramatic-copy"><h1 id="dramatic-title">POTÊNCIA SOB CONTROLE.</h1><p>Reprogramação de motores e pacotes de performance.</p><div class="dramatic-actions">{button('Orçamento no WhatsApp')}{link('Encontre seu pacote','/performance/')}</div></div><nav class="dramatic-services" aria-label="Explore os serviços"><a href="/performance/"><span>01 /</span> REPROGRAMAÇÃO DE ECU</a><a href="/performance/"><span>02 /</span> PACOTES DE PERFORMANCE</a><a href="/education/"><span>03 /</span> ACF EDUCATION</a></nav></section>'''
home=approved_hero+home[home.index('<div class="proof-bar'):]
page('/','Remap, tuning e preparação automotiva em São Paulo','Pacotes de performance, reprogramação de ECU e cursos ACF Education. Fale com a ACF Performance em São Paulo.',home)
def source_paragraphs(name):
    sys.path.insert(0,str(ROOT/'.sites-runtime/python'))
    from bs4 import BeautifulSoup
    soup=BeautifulSoup((ROOT/'research'/f'{name}.html').read_text(encoding='utf-8'),'html.parser')
    el=soup.select_one('.texto.html')
    return [t.strip() for t in el.get_text('\n',strip=True).split('\n') if t.strip()] if el else []
history=source_paragraphs('acf-1-historia')
history_html=''.join(f'<p>{E(p)}</p>' for p in history)
acf=masthead('ACF PERFORMANCE','CONHECIMENTO.<br><em>SEM FRONTEIRAS.</em>','Soluções de performance personalizadas, desenvolvidas em São Paulo desde 2012.')+f'<section class="section wrap split"><img class="feature-image" src="/assets/performance.jpg" alt="Subaru preparado pela ACF" width="394" height="390"><div><h2>UMA HISTÓRIA<br>EM <em>MOVIMENTO.</em></h2><p class="lead">Da calibração de Subaru e Mitsubishi à preparação de BMW nos cinco continentes.</p><div class="actions">{button("Conhecer a história","/acf/1/historia/")}{link("Conhecer a equipe","/acf/3/equipe-performance/")}</div></div></section>'
page('/acf/','A ACF','Conheça a história e a equipe ACF Performance.',acf)
timeline=''.join(f'<div><span class="code">{y}</span><p>{t}</p></div>' for y,t in [('2012','Início do desenvolvimento de soluções de performance personalizadas.'),('2014','Primeira sede. Foco em motores Subaru e Mitsubishi.'),('2015–16','Participação no SEMA Show, em Las Vegas.'),('2018','Retomada da atuação no Brasil, com parcerias em São Paulo.'),('2020','Nova sede própria, com infraestrutura para projetos e capacitação.')])
body=masthead('ACF / HISTÓRIA','DA OFICINA<br>PARA O <em>MUNDO.</em>','Uma trajetória de desenvolvimento, calibração de motores e conhecimento compartilhado.')+f'<section class="section wrap"><div class="timeline">{timeline}</div><div class="article-layout"><aside>{label("NOSSA TRAJETÓRIA")}<p>Texto e conquistas relatados pela ACF. Os recordes são históricos, nas datas informadas, e não uma classificação mundial atual.</p>{link("Fonte original",OFFICIAL+"/acf/1/historia")}</aside><article class="prose">{history_html}<a class="btn btn-line" href="https://www.youtube.com/watch?v=J4JscvxmWuc">Assista ao vídeo da ACF ↗</a></article></div></section>'
page('/acf/1/historia/','História da ACF','Conheça a trajetória da ACF desde 2012, sua presença internacional e conquistas históricas.',body,'/acf/')
team=source_paragraphs('acf-3-equipe-performance')
names=['Ricardo Freitas','Odair Junior','Fabrício Oliveira','Matheus Romano'];people=[]
for i,name in enumerate(names):
    start=team.index(name);end=team.index(names[i+1]) if i+1<len(names) else len(team);role=team[start+1];bio=team[start+2:end]
    people.append(f'<article class="team-member"><div class="team-photo">{placeholder("Retrato de "+name)}</div><div><span class="eyebrow">{E(role)}</span><h2>{E(name)}</h2>{"".join("<p>"+E(p)+"</p>" for p in bio)}</div></article>')
page('/acf/3/equipe-performance/','Equipe Performance','Ricardo Freitas, Odair Junior, Fabrício Oliveira e Matheus Romano: conheça a equipe ACF.',masthead('ACF / EQUIPE','POR TRÁS DE CADA<br><em>PROJETO.</em>','Engenharia, calibração, atendimento e conteúdo. Conheça quem faz a ACF.')+'<section class="section wrap">'+''.join(people)+'</section>','/acf/')
education=masthead('ACF EDUCATION','ENTENDA. CALIBRE.<br><em>EVOLUA.</em>','Para entusiastas e profissionais que querem compreender a teoria e a prática da preparação de motores.',button('Ver os módulos','#modulos'))+f'<section class="section wrap split"><div><h2>A TEORIA ENCONTRA<br>O <em>DINAMÔMETRO.</em></h2><p class="lead">Todos começam pelo Módulo 1. O requisito é ter interesse em aprender.</p><p>O ACF Education apresenta o funcionamento dos motores de combustão interna e as centrais eletrônicas que controlam seu rendimento. Os cursos conectam explicação técnica e experiência prática.</p></div><img class="feature-image" src="/assets/education.jpg" alt="Ricardo Freitas ministrando aula para alunos do ACF Education" width="394" height="390"></section><section class="section wrap light" id="modulos">{label("ESCOLHA SUA ETAPA")}{courses()}<p class="note">Datas, disponibilidade e investimento: {placeholder("agenda e valores atuais dos cursos")}</p></section>'
page('/education/','Cursos de preparação e calibração','ACF Education: Módulo 1 presencial, 16 horas; Módulo 2 híbrido, 15 horas online e 16 presenciais.',education)
course_info=[('1','modulo-1-presencial','MÓDULO 1','PRESENCIAL','16 horas / 2 dias',['História e funcionamento dos motores de combustão interna.','Controladores de motores de ciclo Otto e injeção eletrônica.','Técnicas de calibração considerando economia, durabilidade e performance.','Prática com injeções FuelTech, aquisição de dados e veículo no dinamômetro.'],'Ser entusiasta. Não é necessário ter realizado outro módulo.'),('5','modulo-2-hibrido-parte-online-e-parte-presencial','MÓDULO 2','HÍBRIDO','15 horas online + 16 horas presenciais',['Equipamentos para reprogramação comercial e o negócio de tuning.','Fabricantes de ECUs e estratégias de motores modernos.','Três estratégias de calibração, com ênfase definida pelos alunos.','Aplicação prática das calibrações e aquisição de dados em veículos.'],'Ter concluído o Módulo 1 da ACF. O site informa que não há exceções.')]
for ident,slug,title,form,duration,topics,prereq in course_info:
    source_name=f'education-info-{ident}-{slug}';paragraphs=source_paragraphs(source_name)
    detail=''.join('<p>'+E(p)+'</p>' for p in paragraphs)
    body=masthead('EDUCATION / '+form,title+'.<br><em>CONHECIMENTO APLICADO.</em>','Treinamento ministrado por Ricardo Freitas, fundador e tuner da ACF.')+f'<section class="section wrap course-detail"><article><h2>O QUE VOCÊ<br>VAI <em>APRENDER.</em></h2><ul class="learning">'+''.join('<li>'+E(t)+'</li>' for t in topics)+f'</ul><h3>PRÉ-REQUISITO</h3><p>{prereq}</p><details class="syllabus"><summary>Ler a descrição completa do curso</summary><div class="prose source-copy">{detail}</div></details></article><aside class="enroll"><span class="tag">{form}</span><h3>{title}</h3><dl><div><dt>Carga horária</dt><dd>{duration}</dd></div><div><dt>Instrutor</dt><dd>Ricardo Freitas</dd></div><div><dt>Próxima turma</dt><dd>{placeholder("data")}</dd></div><div><dt>Investimento</dt><dd>{placeholder("valor")}</dd></div></dl>{button("Consultar inscrição",WA+"?text=Tenho%20interesse%20no%20"+title.replace(' ','%20'))}<p class="small">Confirme a agenda, o local das aulas e as condições de inscrição com a equipe.</p></aside></section>'
    schema={'@context':'https://schema.org','@type':'Course','name':title+' - '+form,'description':'Treinamento ACF Education em calibração de motores.','provider':{'@type':'Organization','name':'ACF Performance','url':ORIGIN},'educationalCredentialAwarded':None}
    del schema['educationalCredentialAwarded']
    page(f'/education/info/{ident}/{slug}/',title+' — '+form,'Conheça conteúdo, formato, carga horária e pré-requisitos deste curso ACF Education.',body,'/education/',schema)
catalog=json.loads((ROOT/'research/catalog.json').read_text(encoding='utf-8'))
(DIST/'data').mkdir(exist_ok=True);(DIST/'data/catalog.json').write_text(json.dumps(catalog,ensure_ascii=False,separators=(',',':')),encoding='utf-8')
brands=''.join(f'<option value="{b["id"]}">{E(b["name"])}</option>' for b in catalog['brands'])
filters=f'<div class="filter-field"><label for="brand">Fabricante / aplicação</label><select id="brand"><option value="">Selecione</option>{brands}</select></div>'+''.join(f'<div class="filter-field"><label for="{i}">{n}</label><select id="{i}" disabled><option value="">{p}</option></select></div>' for i,n,p in [('model','Modelo','Escolha o fabricante'),('year','Ano / geração','Escolha o modelo'),('version','Versão / motor','Escolha o ano')])
perf=masthead('PERFORMANCE / CATÁLOGO','ENCONTRE O SEU<br><em>PRÓXIMO NÍVEL.</em>','Pacotes de reprogramação por fabricante, modelo e motorização. Confira as especificações e converse com a equipe.',button('Tirar dúvidas no WhatsApp'))+f'<section class="section wrap catalog"><div class="section-head"><h2>QUAL É O<br><em>SEU CARRO?</em></h2><p>Catálogo ACF consultado em 22/09/2026.<br>Confirme disponibilidade e valores antes da contratação.</p></div><div class="filters">{filters}</div><p id="catalog-status" role="status">Selecione o fabricante para começar.</p><div id="catalog-results"><div class="empty-state"><span class="code">ACF / PERFORMANCE</span><h3>UM PROJETO COMEÇA<br>COM A APLICAÇÃO CERTA.</h3><p>Use os filtros para ver os pacotes publicados para seu carro.</p></div></div><noscript><p>Ative JavaScript para usar os filtros ou <a href="{OFFICIAL}/performance/">consulte o catálogo original</a>.</p></noscript></section>'
page('/performance/','Pacotes de performance','Consulte pacotes, preços, ganhos de potência e torque, fotos e gráficos publicados no catálogo ACF.',perf)
media=masthead('ACF / MEDIA','CONTEÚDO PARA<br>QUEM <em>VIVE CARROS.</em>','YouTube, Tunercast e Instagram. Conhecimento e conversas sobre preparação, potência e alta performance.')+f'<section class="section wrap">{media_cards()}<div class="shop-band"><img src="/assets/merch.jpg" alt="Moletom da linha ACF Performance" width="121" height="121" loading="lazy"><div>{label("LINHA ACF")}<h2>VISTA ESSA <em>PAIXÃO.</em></h2><p>Camisetas e moletons da ACF Performance.</p></div>{button("Visitar a loja","https://www.lolja.com.br/acfperformance")}</div><p class="note">Curadoria de projetos, episódios e posts para esta página: {placeholder("links e imagens aprovados")}</p></section>'
page('/media/','Media — YouTube, Tunercast e Instagram','Explore o canal ACF Performance, o podcast Tunercast, o Instagram e a loja oficial.',media)
portal=masthead('ACF / REVENDEDORES','PARCERIA QUE<br>GERA <em>PERFORMANCE.</em>','Acesso restrito aos revendedores da ACF Performance.')+f'<section class="section wrap portal-grid"><article class="access-panel"><span class="code">01 / ACESSO EXISTENTE</span><h2>PORTAL DO<br><em>REVENDEDOR.</em></h2><p>Continue para o sistema oficial e utilize suas credenciais de revendedor.</p>{button("Acessar o portal oficial",OFFICIAL+"/portal/")}<p class="small">O login é realizado no ambiente original da ACF.</p>{link("Recuperar senha",OFFICIAL+"/portal/recuperar-senha.asp")}</article><article class="access-panel secondary"><span class="code">02 / ATENDIMENTO</span><h2>PRECISA<br>DE <em>AJUDA?</em></h2><p>Fale com a equipe para informações sobre acesso e atendimento aos revendedores.</p>{button("Falar com a ACF",WA,True)}<p>Cliente final? {link("Acesse sua área",OFFICIAL+"/area-do-cliente/")}</p></article></section>'
page('/portal/','Portal do revendedor','Acesso ao portal oficial dos revendedores ACF Performance e suporte da equipe.',portal)
contact=masthead('ACF / CONTATO','SEU PROJETO<br><em>COMEÇA AQUI.</em>','Fale com a ACF Performance em São Paulo. Orçamentos, cursos e dúvidas sobre o seu carro.',button('Conversar no WhatsApp'))+f'''<section class="section wrap contact-grid"><div><h2>VAMOS ENTENDER<br>O SEU <em>PROJETO.</em></h2><form id="contact-form"><label for="name">Nome *</label><input id="name" name="nome" required autocomplete="name" maxlength="100"><div class="form-two"><div><label for="email">E-mail</label><input id="email" name="email" type="email" autocomplete="email" maxlength="150"></div><div><label for="phone">Telefone</label><input id="phone" name="telefone" type="tel" autocomplete="tel" maxlength="30"></div></div><label for="city">Cidade</label><input id="city" name="cidade" autocomplete="address-level2" maxlength="100"><label for="message">Mensagem *</label><textarea id="message" name="mensagem" rows="5" required maxlength="1500" placeholder="Conte qual é o seu carro ou curso de interesse."></textarea><p class="small muted">Ao continuar, você poderá revisar e enviar a mensagem no WhatsApp. Este formulário não envia e-mail nem salva seus dados.</p><button class="btn" type="submit">Preparar mensagem <span aria-hidden="true">↗</span></button><div id="contact-result" hidden><p role="status">Mensagem preparada. Revise e conclua o envio no WhatsApp.</p><a id="whatsapp-message" class="btn" target="_blank" rel="noopener">Abrir WhatsApp ↗</a></div></form></div><aside class="address-panel"><span class="eyebrow">VISITE A ACF</span><h3>SÃO PAULO.<br>VILA MARIANA.</h3><address>Av. Doutor Ricardo Jafet, 1050<br>Vila Mariana · São Paulo, SP<br>CEP 04260-000</address><a class="phone" href="tel:+5511984496047">(11) 98449-6047</a>{link('Abrir no Google Maps','https://www.google.com/maps/search/?api=1&query=Av.+Dr.+Ricardo+Jafet+1050+Sao+Paulo')}<p class="note">Horário de atendimento:<br>{placeholder('dias e horários')}</p></aside></section>'''
page('/contato/','Contato e orçamento','Fale com a ACF no WhatsApp (11) 98449-6047. Av. Doutor Ricardo Jafet, 1050, Vila Mariana, São Paulo.',contact)
(DIST/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" fill="#101114"/><path d="M5 26 15 6h6l6 20h-6l-1-5h-7l-2 5zm10-10h4l-1-6z" fill="#e00000"/></svg>')
routes=['/','/acf/','/acf/1/historia/','/acf/3/equipe-performance/','/performance/','/education/','/media/','/portal/','/contato/']+[f'/education/info/{c[0]}/{c[1]}/' for c in course_info]
(DIST/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+ORIGIN+r+'</loc></url>' for r in routes)+'</urlset>',encoding='utf-8')
(DIST/'robots.txt').write_text('User-agent: *\nDisallow: /\n# Private design preview. Enable indexing only after final content approval.\n')
(DIST/'404.html').write_text('<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Página não encontrada. Volte para a ACF Performance."><meta name="robots" content="noindex,nofollow"><title>Página não encontrada | ACF</title><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/approved-home.css"><main class="page-hero wrap"><p>404 / ACF PERFORMANCE</p><h1>PÁGINA NÃO<br>ENCONTRADA.</h1><a class="btn" href="/">Voltar ao início ↗</a></main></html>',encoding='utf-8')
print(f'Built {len(routes)} pages + 404. Catalog: {len(catalog["brands"])} categories.')
